/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./Src/romancalc-test.check" instead.
 */

#include <check.h>

#line 1 "./Src/romancalc-test.check"
#include "romancalc.h"
#include <stdlib.h>

START_TEST(romancalcTest)
{
#line 5

	// check roman2dec_char
	ck_assert_int_eq(roman2dec_char('1'), 0);
	ck_assert_int_eq(roman2dec_char('m'), 1000);
	ck_assert_int_eq(roman2dec_char('X'), 10);
	ck_assert_int_eq(roman2dec_char('b'), 0);
	

	// check roman2dec_str
	ck_assert_int_eq(roman2dec_str(""), 0);
	ck_assert_int_eq(roman2dec_str("m"), 1000);
	ck_assert_int_eq(roman2dec_str("lXxXvIiI"), 88);
	ck_assert_int_eq(roman2dec_str("MMMACIX"), 0);


	// check dec2roman 
	char buffer[20];
	dec2roman(1, buffer);
	ck_assert_str_eq(buffer,"I");
	dec2roman(2, buffer);
	ck_assert_str_eq(buffer,"II");
	dec2roman(4999, buffer);
	ck_assert_str_eq(buffer,"MMMMCMXCIX");

	// check isItValidRomanNumeral
	ck_assert_int_eq(isItValidRomanNum("X"),1);
	ck_assert_int_eq(isItValidRomanNum("IIX"),0);
	ck_assert_int_eq(isItValidRomanNum("XBI"),0);
	ck_assert_int_eq(isItValidRomanNum("XXXX"),0);
	ck_assert_int_eq(isItValidRomanNum("DD"),0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, romancalcTest);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
